### ISSUE TITLE
Shorten commit message in the issue body

### ISSUE THREAD

**Issue by simoneb** [nearform-actions/github-action-notify-release#391]
Now that github includes the PR name in the markdown, it looks like we have some redundancy we could get rid of to make the issue body more readable.

Let's maybe inspire from how GitHub builds release notes in releases to get a sense of whether it makes sense to introduce this.

![image](https://user-images.githubusercontent.com/20181/212855182-db3dd37e-0874-4ca3-9577-36ab319286eb.png)

**Comment by simoneb** [comment]
An example of release notes can be found e.g. [here](https://github.com/nearform/optic-release-automation-action/releases). Note that differently from release notes, here we need to print list of commits, which makes it a little more difficult, e.g. there can be multiple commits within the same PR, so the message of the commit may not necessarily match the title of the PR. maybe we should group the commits by PR? what if a commit what done without a PR?

**Comment by davideroffo** [comment]
Based on your comment I propose the following solution / template structure.

In the created issue we can:
    - group the commits by PR:

```markdown
[PR name included by GitHub] 1:
    - commit 1
    - commit 2
    - ...
    - commit N
[PR name included by GitHub] 2:
    - commit 1
    - commit 2
    - ...
    - commit N
...
[PR name included by GitHub] N:
    - commit 1
    - commit 2
    - ...
    - commit N
```

If a commit was done without a PR we can include it in a separate group/category:

```markdown
Commits without a PR:
    - commit 1
    - commit 2
    - ...
    - commit N
```

What do you think?

**Comment by simoneb** [comment]
I like the idea but I think we should also add an additional condition. If the PR, as is often the case, had a single commit, then we probably don't need to do the dotted list below the PR name. also I'm not sure about the relationship between the PR title and the commit message of the single commit. I assume the normally match (if there's a single commit in a PR), but I don't think that's necessarily the case either.

Ultimately, let's try this approach and see what we get, and let's add the above simplification so that a PR with a single commit gets a single line instead of the PR line plus the (single) commit unordered list.

**Comment by davideroffo** [comment]
```markdown
[PR name included by GitHub] 1:
    - commit 1
    - commit 2
    - ...
    - commit N
[PR name included by GitHub] 2:
    - commit 1
    - commit 2
    - ...
    - commit N
...
[PR name included by GitHub] N:
    - commit 1
    - commit 2
    - ...
    - commit N

Commits without a PR:
    - commit 1
    - commit 2
    - ...
    - commit N

- commit 1 related to a PR with single commit
- commit 2 related to a PR with single commit
- ...
- commit N related to a PR with single commit
```

While developing this feature, would be great to have a personal repo with these unreleased-commits state:

- 1 or multiple PRs merged with two or more commits
- 1 or multiple PRs merged with one commit
- 1 or multiple direct-commits on main

**Comment by simoneb** [comment]
feel free to create one in your own account and set it up that way :)
