### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by till** [nearform-actions/github-action-notify-release#817]
Is this mostly based on days, or on commits?

I am trying to use your action in a repository. One of the things I noticed was that it only works based on releases. It doesn't seem to inspect the tags in the repository at all. Then I created a release (for a tag we made last week), but now it doesn't seem to recognise the commits in main since then.

When I go on GitHub, and inspect my release, it says, "12 commits to main since then". I am guessing you use another mechanism to figure out commits?

**Comment by simoneb** [comment]
The action's logic is this: if any new commits are in the repo after X days since the last release, it will open the issue. So yes, it works based on releases. The date of the last release is the date when we start counting days. Does this clarify it?

**Comment by till** [comment]
Yes, thanks very much. I'll send a PR to the readme if you like. :)
